import {Navbar, Footer} from '@/app/components'
import './globals.css'
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'The Royal Motors',
  description: 'Generated by Bilawal',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
